### ISSUE TITLE
Implement direct mutation support?

### ISSUE THREAD

**Issue by epeli** [dai-shi/reactive-react-redux#14]
Posted this initially to #10 but it's offtopic over the so I'm pulling it here.

Have you considered supporting mutating the state too? I think this method could be used to implement very mobx like api for Redux.

Eg. add support for this:

```js

function Counter() {
	const state = useReduxState();
	return <button onClick={() => state.count++}>{count}</button>;
}
```

The implementation could go like this:

1. User does `state.foo.bar = 1` in a event handler
   - it should be banned during the render tick
2. Record that change as a immer patch `{"op": "replace", "path": ["foo", "bar"], "value": 1}`
3. Create redux action from like

```js
{
  type: "IMMER_PATCH",
  patch:  {"op": "replace", "path": ["foo", "bar"], "value": 1},
}
```

4. And apply it using `applyPatches` from immer in a reducer. It would support all the redux goodies: Devtools, Time-travel, action serialization etc.

Kinda getting excited about this 😃

**Comment by dai-shi** [comment]
> Have you considered supporting mutating the state too?

Sort of. There was a suggestion and I had a dreaming idea to combine immer and this for more performance. That's only about mutations in reducers.
I haven't thought about mutations in event handlers.

Honestly, I'm not a big fan of the mutation style in event handlers.
What I think is good about Proxy is specialized for performance optimization.
Changing the semantics with Proxy doesn't seem very intuitive to me.

That said, I think `useReduxState` can be a building block and I'm happy with it.
So, I'm open for extending it reasonably so that someone can develop a custom hook based on it to support mutations.

> Kinda getting excited about this 😃

I don't mean to stop you. I encourage you going foward.
@theKashey might have a word or two about deep proxies and set handlers.

**Comment by theKashey** [comment]
`immer` is working like a magic. But

> Have you considered supporting mutating the state too?

This is something every new comer want, this is something every author of a brand new state management library want to introduce.

This is something I dont like to have. Idea is to separate actions and changes. To move side effects to `sagas`, to respond to one action from multiple reducers, to have easy way to debug and easy way to reason about.

Something like teaming Redux and useReducer - might be cool, but also catastrophic.
----
From another point of view - yes, this could be done.

**Comment by luisherranz** [comment]
I was about to open a similar issue to discuss state mutations.

I agree with @theKashey, mutations should only happen inside reducers.

But apart from that, one of the worse developer experience of redux is precisely maintaining immutability.

I've quickly tested this:
```js
const reducer = (previousState = initialState, action) => {
  const state = { ...previousState };
  switch (action.type) {
    case "increment":
      state.counter += 1;
      break;
    case "decrement":
      state.counter -= 1;
      break;
    case "setText":
      state.text = action.text;
      break;
  }
  return state;
};
```

versus this (original example):
```js
const reducer = (state = initialState, action) => {
  switch (action.type) {
    case 'increment':
      return { ...state, counter: state.counter + 1 };
    case 'decrement':
      return { ...state, counter: state.counter - 1 };
    case 'setText':
      return { ...state, text: action.text };
    default: 
      return state;
  }
};
```

And it seems to work great (because this library and proxyEqual are awesome, by the way).

Do you know the limitations of this? I've read about the limitations of the spread operator in the tracking part but I can't think of any problem in the mutation part. Are we breaking any optimization?

If there are no limitations, what do you think about improving the developer experience of the reducers patching the redux store so it passes a cloned state object and then returns it?

The final reducer could be:
```js
const reducer = (state, action) => {
  // const state = { ...previousState }; <-- this is only boilerplate, could be done by patched store.
  switch (action.type) {
    case "increment":
      state.counter += 1;
      break;
    case "decrement":
      state.counter -= 1;
      break;
    case "setText":
      state.text = action.text;
      break;
  }
  // return state; <-- this is only boilerplate, could be done by patched store.
};
```

**Comment by theKashey** [comment]
> Do you know the limitations of this? I've read about the limitations of the spread operator in the tracking part but I can't think of any problem in the mutation part.

https://github.com/theKashey/memoize-state/issues/26 - the only limitation so far. We likely have a solution for spreads.

**Comment by epeli** [comment]
@theKashey 	

> This is something every new comer want, this is something every author of a brand new state management library want to introduce.

> This is something I dont like to have. Idea is to separate actions and changes.

I actually agree with you on this 100%. I'd never actually use it on real apps because mutating state like that inside a component makes it harder to test the state transforms.

But I would still find it useful for prototyping and introducing newcomers to the concepts. The fact that you could mutate the state directly in a event handler doesn't doesn't mean you should write the mutation code in there. One should of course create a standalone functions for it like:

```js
function setUserEmail(state, userId, email) {
	state.users[userId].email = email;
}
```

That's not really _that_ different from dispatching an action that does that using Immer inside a reducer but it's a whole lot simpler to explain for newbies. It's literally just a plain JavaScript function. Testable and easy to understand.

I've actually created [immer-reducer](https://github.com/epeli/immer-reducer) which gets pretty close to this but it does not allow mutation code directly inside components. Also the official Redux Starter Kit is doing something similiar with `createReducer`.

**Comment by dai-shi** [comment]
Closing this because there's no plan for this in the near future. But, feel free to reopen it for further discussion.
