### ISSUE TITLE
Question about re-evaluation strategy

### ISSUE THREAD

**Issue by Ziriax** [dai-shi/reactive-react-redux#37]
This looks like a very nice library, congratulations! 

I was wondering, suppose a component reads `a.b.c` from tracked state `a`. Suppose a new state `a` is reduced, and `a.b` also "changes", but `a.b.c` remains the same. I guess in this case the component will not re-render? In other words, to determine if a component should re-render, you 
always compare the leaf nodes of the dependency tracking graph?

Is this reasoning correct?

**Comment by dai-shi** [comment]
Good point.
I think so. (The implementation of deepProxy is very complicated.)

I made an example.
https://codesandbox.io/s/reactive-react-redux-example-s28eq
Yes, it works as you expect.

**Comment by dai-shi** [comment]
> always compare the leaf nodes

This is correct.
That brings us to a caveat. If a component reads both `a.b.c` and `a.b`, it will treat as if the component only reads `a.b.c` because `a.b` is not a leaf. So, even if `a.b` is changed, but `a.b.c` is kept the same, the component will not re-render.

**Comment by Ziriax** [comment]
Oh but if a component reads both `a.b` and `a.b.c.`, it should have two tracked paths in the tree no? Maybe this library doesn't work like that, but my own MobX like experiment in C# performed tracking per object/property pair, not per object only.

**Comment by dai-shi** [comment]
This is because we share proxy object.
```js
const x = a.b;
const y = a.b;
// we expect x === y
```

Now, let's say we do the following:
```js
// pattern 1
const x = a.b;
const y = a.b;
const z = y.c;
```
we can't distinguish this from the following:
```js
// pattern 2
const z = a.b.c.;
```

In other words, we end up with the identical tracked paths with both pattern 1 and pattern 2.

Is this reasonable? Do you have an idea with your experiment?

**Comment by dai-shi** [comment]
Technically, it's not a list of tracked paths like `[['a', 'b', 'c'] , ['a', 'b', 'd']]`,
 but a single tracked tree like `{ a: { b: { c: LEAF, d: LEAF } }`.

**Comment by Ziriax** [comment]
You are right, this isn't that simple. 

IMHO it is not the evaluated leaf paths to expressions that should be considered for re-rendering, but the shortest paths ending up in the components being rendered.

So if you have a component that renders `<Foo x={abc}/> with `const ab=a.b; const abc=ab.c` then only `a.b.c` needs to be considered. If instead `<Bar x={abc} y={ab}/>` is rendered, then `ab` is the only one to be considered. But I guess you can't know this.

But I have no practical experience with this in JavaScript, Proxies and React, so I might be very wrong here.

**Comment by dai-shi** [comment]
New ideas/insights are generally welcome. 😉 

> But I guess you can't know this.

Yeah.

One possible misunderstanding you and maybe others might have is that it doesn't stop tracking for child components.
This is very unique to this library (more precisely the family of my libraries: This, [[1]](https://github.com/dai-shi/react-tracked) and [[2]](https://github.com/dai-shi/svelte3-redux)).
Technically, we can't know when render function ends. React doesn't provide such a feature.
So, I rather keep tracking forever...
This means it will keep tracking even with the inside of `<Foo x={abc}/>` or `<Bar x={abc} y={ab}/>`.
In other words, most likely the leaf nodes are primitives like strings and numbers.
The exception is probably memoization and maybe some others.
It does best to work with memoization but there must be pitfalls.
I'd love to get feedback from everyone.

The current approach and implementation should be pretty good.
I spent quite a long time to reach this point. I can say it's almost optimal, meaning a good trade-off balance between the usability and the performance.

If there's a practical use case this approach doesn't work, I will reconsider and maybe tweak it (or gave up such a use case).
So again, any example to break this tracking approach is welcome, preferably practical ones instead of hypothetical ones.

**Comment by dai-shi** [comment]
Closing this. Feel free to re-open it for further discussion.

**Comment by Ziriax** [comment]
Thanks for your feedback! I've been thinking about it, and I my gut feeling says your approach is valid.
