### ISSUE TITLE
Testing Environment Slowdown

### ISSUE THREAD

**Issue by JackCA** [dai-shi/reactive-react-redux#42]
I'm noticing a huge degradation in my test runner performance after switching to `reactive-react-redux`. I use jest and create pretty large/deep redux-connected components pretty rapidly.

Is there something that could be affecting the performance here? Should things be torn down in some way?

**Comment by dai-shi** [comment]
Thanks for reporting. I'm not aware of the issue. Sounds like it should be improved.
Is it possible for you to create a small reproduction?

**Comment by JackCA** [comment]
I attempted to create a small app to reproduce the discrepancy but was unsuccessful. It may be that I didn't full replicate my state but it will be difficult to reproduce this I think.

Working backwards though, is there setup overhead with this vs raw react-redux?

**Comment by dai-shi** [comment]
I'm not aware of considerable overhead compared to react-redux.
The major difference is the use of Proxies. Could it affect a large scale test? Not sure.
What is your jest `testEnvironment`?

If you could try using only `useSelector` from reactive-react-redux, which doesn't rely on Proxies, it might reveal if the cause is useTrackedState related or not.

**Comment by JackCA** [comment]
I can't reproduce now. Apologies for the noise 😬
